name: Run Tests

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  tests:
    name: Tests (PHP ${{ matrix.php-versions }} on ${{ matrix.operating-system }})
    runs-on: ${{ matrix.operating-system }}
    strategy:
      fail-fast: false
      matrix:
        operating-system: [ubuntu-18.04, ubuntu-latest, windows-latest, macos-latest]
        php-versions: ['8.0']

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
          php-version: ${{ matrix.php-versions }}
          extensions: dom, curl, libxml, mbstring, zip, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, fileinfo
          coverage: none

    - name: Install dependencies
      run: composer install --prefer-dist --no-interaction --no-progress

    - name: Run PHP tests
      run: vendor/bin/phpunit
